schema_version = "1.0.0"

id = "multi_range_renderer"
version = "1.2.0"
name = "Multi Range Renderer"
tagline = "Render multiple frame ranges with selected cameras"
maintainer = "kunemann (www.koen.work)"
type = "add-on"

website = "https://www.koen.work"

tags = ["Render"]

blender_version_min = "4.2.0"

license = ["SPDX:MIT"]

copyright = [
  "2025 kunemann",
]

[build]
paths_exclude_pattern = [
  "__pycache__/",
  "*.pyc",
  ".DS_Store",
  "/.git/",
  "/*.zip",
]
